### PR TITLE
feat(ctag): add ctag component

### PR DESCRIPTION
**Pull request by Shyrro**
Signed-off-by: Shyrro <zsahmane@gmail.com>

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes
      /start features)

## Pull request type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Current behavior of the tag is the same as the Tag in Chakra ui React.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I noticed that Cypress tests were loading infinitely, so i opened another PR to fix them : (#147 )

Also, couldn't update the docs in the Vitepress, nothing showed up.

### CODE REVIEW

**Review by codebender828 — CHANGES_REQUESTED** [review]
Thank you @Shyrro for this pull request!

I appreciate all the help you're lending to the project. The code on this PR looks pretty good. The only think I think that it's missing is a working deployment of the demos. It seems the rendering of the playground is broken on the deploy preview.

Do you think you could resolve that before we merge?

**Comment by Shyrro** [comment]
Hi @codebender828 !

Thanks for the review, i'll definitely try to fix that !

Can you just confirm to me what is broken? It seems to me that when i go to the staging, everything breaks after i click on the Accordion, if i don't and click elsewhere (buttons, icons etc.) everything works fine.

If i go here : https://chakra-ui-vue-next-playground-git-fork-shyrro-3e0cb3-chakra-ui.vercel.app/c-icon/examples/base-icon

I see the base icon, but if i click on the Accordion and click back on anything else, nothing works anymore, can you confirm that please? 

Thank you and i'll try to fix that ASAP ☺️

**Comment by Shyrro** [comment]
Hi @codebender828 !

Seems that the playground was broken on `develop` so i fixed it in another PR (#151 ) but i cherry picked the commit in this PR so that you can check that the Tags are working fine.

Let me know if there is anything else that needs to be changed,

Thanks !

**Comment by codebender828** [comment]
Thank you @Shyrro ! Will go ahead and merge this

**Pull request merged**
